site_name: My Docs
theme:
  name: 'material'
  features:
    content:
      math: true
      copycode: trues

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_signature: true
            sorting: source

nav:
  - Home: index.md
  - API Reference:
      - Photonic Crystal: photonic_crystal.md
  - Installation: installation.md



watch: 
  - src