# .github/workflows/deeploy.yml
name: Deploy MkDocs Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Create virtual environment
        run: python -m venv docs/mkdocs_venv

      - name: Activate virtual environment and install dependencies
        run: |
          source docs/mkdocs_venv/bin/activate
          pip install --upgrade pip
          pip install -r docs/requirements-docs.txt

      - name: Build MkDocs site
        run: |
          source docs/mkdocs_venv/bin/activate
          mkdocs build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site